name: Test

on:
  pull_request:
    branches:
      - master
      - develop
      - staging

jobs:
  Test:
    runs-on: ubuntu-latest
    container: golang:1.17.3

    services:
      postgres:
        image: postgres:13.4-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Run Test
        env:
            TEST_DATABASE_HOST: postgres
            LOG_LEVEL: ${{ secrets.TEST_LOG_LEVEL }}
        run: go test ./... -p 1 -v
